version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: projetoDocker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:senha@db:5432/projetoDocker
    ports:
      - "8080:8080"

volumes:
  pgdata:
